default: &default
  adapter: postgresql
  encoding: unicode
  username: core
  password: test
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5


development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: shared
  host: shared.cirjgw1iubqm.us-west-2.rds.amazonaws.com
  username: bunge
  port: 5432
  password: CORPSHARED
  pool: 5

  
# test:
#   <<: *default
#   database: core_test

